#

# PATCH_SAMPLING_SIZE_INSIDE_BBOX = 100
# PATCH_MINIMUM_NO_OF_SAMPLES_OF_BBOX = 10

PATCH_SAMPLING_SIZE_INSIDE_BBOX = 10000
PATCH_MINIMUM_NO_OF_SAMPLES_OF_BBOX = 1000
PATCH_SAMPLE_BOX_SIZE = 299
PATCH_SIZE = 299

PATCH_TUMOR_PIXELS_RATIO_THRESHOLD = 0.9
PATCH_NON_TUMOR_RED_PIXELS_RATIO_THRESHOLD = 0.85

DATASET_NAME = "lymph_nodes"